Fix ndk-gdb support for devices that don't set ro.product.cpu.abilist
Previously, the script crashed:

    AttributeError: 'NoneType' object has no attribute 'split'

AndroidDevice.get_prop uses "adb shell getprop NAME" to read a property,
which does not distinguish between an unset property and a property set to
"".  ("adb shell getprop" *does* distinguish, but I think there are parsing
issues with properties containing newlines?)

AndroidDevice.get_prop never returns "". If a property is unset or blank,
get_prop returns None.

Fix the three calls sites to get_prop.

Test: run ndk-gdb on an old 4.1.2 device that doesn't set abilist
Test: verify that int(None) and int("123 x") are caught
Change-Id: Iffc4b73ea89bc71b7b6ea3e00f4f43364857f6ef