Replace distutils copy_tree, exclude tmp files
distutils is deprecated and may be removed in an upcoming Python
release.

The function currently copies the LLVM toolchain's Python 3
installation, which may contain temporary files in __pycache__ if its
Python modules have been loaded. There is currently a race condition in
checkbuild.py where loading a Python module briefly creates a temp file
that breaks a concurrent copy_tree invocation:

distutils.errors.DistutilsFileError: can't copy
  '/buildbot/src/android/master-ndk/out/linux/android-ndk-r24-canary/
  toolchains/llvm/prebuilt/linux-x86_64/python3/lib/python3.9/
  __pycache__/selectors.cpython-39.pyc.139731628119184':
  doesn't exist or not a regular file

Fix the race by skipping __pycache__ using shutil.copytree's ignore
parameter. Multiple source dirs are merged, so also pass
dirs_exist_ok=True, which was added in Python 3.8. Change the shebang
to python3.

Bug: none
Test: checkbuild.py, manual
Change-Id: I5cce7b53359672eb6acd9d9bf48cc87f3dccfae6